__default__:
  job-name: "{rule}"
  partition: normal
  time: 180 # minutes
  nodes: 1
  ntasks: 4
  mem: 32gb
  output: "log/{rule}-%j.out"
  error: "log/{rule}-%j.err"

ExcordTumors:
  partition: haswell
  time: 2880 
  mem: 128gb 

ExcordCtrls:
  partition: haswell
  time: 2880 
  mem: 128gb 

MakeGiggleIndexTumors:
  partition: haswell
  time: 10080 
  mem: 64gb 

MakeGiggleIndexCtrls:
  partition: haswell
  time: 10080 
  mem: 64gb

MakeSTIXIndexTumors:
  partition: haswell
  time: 2880 
  mem: 128gb

MakeSTIXIndexCtrls:
  partition: haswell
  time: 2880 

gridss:
  partition: haswell
  time: 4320 
  ntasks: 8 
  mem: 32gb

RunManta:
  partition: haswell
  time: 4320 
  ntasks: 64
  mem: 128gb 

delly:
  partition: haswell
  time: 4320 
  ntasks: 2

smoove:
  partition: haswell
  time: 4320 
  ntasks: 2

gridss_wes:
  partition: haswell
  time: 4320 
  ntasks: 8 
  mem: 32gb

RunMantaWes:
  partition: haswell
  time: 4320 
  ntasks: 64
  mem: 128gb 

delly_wes:
  partition: haswell
  time: 4320 
  ntasks: 2

smoove_wes:
  partition: haswell
  time: 4320 
  ntasks: 2

cnvkit:
  partition: haswell
  time: 10080 
  ntasks: 8 
  mem: 32gb