# TODO leave blank and let user fill out once they've cloned
# the repository on their system.

# manta install setup
install_dir: '/home/msubirana/Documents/phd/repos/cancer-sv-pipeline/install_dir'
manta_version: '1.6.0'

# excord install setup
excord_version: '0.2.4'

# duphold install setup
duphold_version: '0.2.3'

# define sample file to carry the analysis
# path,type,experiment
# path of the file
# type: "tumor" or "control"
# experiment: "WGS" or "WES"
samples_csv: 'conf/samples.csv'

# define bam directory where to carry out the analysis
# we assume that the index files, tumor and ctrl are located in the same directory.
bam_dir: '/home/msubirana/Documents/phd/sv_prove'

# define extension of tumor and ctrl bams (example "_TI" for tumors and "_BL" for ctrls)
tumor_ext: '_TI'
ctrl_ext: '_BL'


# path to reference fasta.  We assume the fasta index is located in the same directory.
reference: '/mnt/lp-lab1/refs/GCA_000001405.15_GRCh38_no_alt_analysis_set/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa'

# path to the base directory for the pipeline outputs.
outdir: '/home/msubirana/Documents/phd/repos/cancer-sv-pipeline/results'

# path to exclude bed regions
exclude_bed: 'data/exclude_list.bed'

# Gene annotation database
refFlat: 'data/refFlat.txt'

