# TODO leave blank and let user fill out once they've cloned
# the repository on their system.

# manta install setup
install_dir: '/home/msubirana/Documents/phd/repos/cancer-sv-pipeline/install_dir'
manta_version: '1.6.0'
excord_version: '0.2.4'
duphold_version: '0.2.3'
# for now I've chosen keep tumor and normal bams
# in separate directories.
# 
# That will allow us to just specify the directories
# of tumor/normal, then we just create a list of all
# bam/crams in a directory.
# 
# We assume that the index files are located in the same directory.
bam_dir: '/home/msubirana/Documents/phd/sv_prove'
tumor_dir: '/home/msubirana/Documents/phd/sv_prove'
normal_dir: '/home/msubirana/Documents/phd/sv_prove'

# path to reference fasta.  We assume the fasta index is
# located in the same directory.
reference: '/mnt/lp-lab1/refs/GCA_000001405.15_GRCh38_no_alt_analysis_set/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa'
# path to the base directory for the pipeline outputs.
outdir: '/home/msubirana/Documents/phd/repos/cancer-sv-pipeline/results'

# path to exclude bed regions
exclude_bed: '/home/msubirana/Documents/phd/repos/cancer-sv-pipeline/workflow/data/exclude_list.bed'